### ISSUE TITLE
Memory leak in Context object

### ISSUE THREAD

**Issue by mattbab** [chriseldredge/Lucene.Net.Linq#35]
The `Context` class in _Context.cs_ depends on a local `SearcherClientTracker` object (instance name `tracker`) which itself is disposable however `Context` does not expose the ability for a client app to dispose of it. This results in hemorrhaging memory when a `LuceneDataContext` is instantiated for each request (identifying case was in a WCF service).

I've coded a fairly dirty and ineffective workaround by making the `Context` disposable, disposing of its `tracker` instance in `Context.Dispose`, and disposing of the `Context` instance in the `LuceneDataContext.Dispose` method. This resolves the memory leak but causes an unfortunate decline in scalability (i.e. performance blows at high volume). The scalability issue is simply worked around by forcing my WCF service to act as a singleton (safe because the library is thread-safe), but is far from ideal.

The second issue might be addressed by reviewing overall library design to move heavy state to lower/lesser used abstractions in the stack, but such changes are fairly invasive and might be hard to swallow. Wondering if you have any ideas on how to address it otherwise.

Let me know if you would like to see a repro or pull request for more information.

Thanks.

**Comment by chriseldredge** [comment]
`LuceneDataProvider`, and `Context` alongside, are intended to be long-lived single instance per `Directory` objects in an application lifecycle. If you are creating a new instance per request, I'd imagine you are paying a rather large penalty in CPU and temporary memory usage in general due to initialization activities. Additionally, creating a new `LuceneDataProvider` per request would cause a new `IndexSearcher` to be created per request, resulting in loss of any built-in caching provided by Lucene (such as the Field Cache). `IndexSeacher` is thread-safe and is most efficient when reused for multiple queries until the index needs to be reloaded due to a commit. `Context` is designed to automatically reload the `IndexSearcher` after a commit so that changes in a session appear as soon as the session is committed.

One approach you may try with WCF is to use the `Ninject.Extensions.Wcf` package (available on nuget.org) and create your `ServiceRoute` using `NinjectDataServiceHostFactory` to inject dependencies into your service. This way you can have per-request instances of your service but still have `LuceneDataProvider` be tied to the application lifecycle.

**Comment by mattbab** [comment]
Ok thanks for the recommendations. I'll work through it.

**Comment by mattbab** [comment]
I understand that my original use of the library did not conform to its intended use, but following .NET best practices, why wouldn't you dispose of the Context when the Provider is disposed (especially considering the known memory leak)?

**Comment by chriseldredge** [comment]
That's a fair point. Fixed in 3588f78559b46f2a44e3e99fcdcdcd918891f971. I'll close the issue when a release is published to nuget.org.

**Comment by mattbab** [comment]
Great, thank you. I haven't run into it yet, but would bet that the LuceneSession class will have the same issue.

**Comment by chriseldredge** [comment]
The client is responsible for disposing LuceneSession, typically in a `using` block. Sessions are scoped to an operation and should be disposed when the operation is completed.

**Comment by chriseldredge** [comment]
Released in 3.2.53.
