### ISSUE TITLE
Other Lucence.NET commands

### ISSUE THREAD

**Issue by emdadgar2** [chriseldredge/Lucene.Net.Linq#51]
Is there any way to query agains another Lucence.NET commands like SpellChecker or MoreLikeThis or DocFreq?

**Comment by chriseldredge** [comment]
I just added a sample for MoreLikeThis in [MoreLikeThisSample](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Samples/MoreLikeThisSample.cs).

I think you would handle spell checking outside of LINQ since you want the raw terms and not what comes through analysis and query transformation.

You could do something similar to the MoreLikeThis sample for DocFreq.

**Comment by emdadgar2** [comment]
Thanks, but DocFreq output is a keyword and freq. number that different from original structure.
Can you create sample for DocFreq too?

Thanks again

**Comment by chriseldredge** [comment]
The MoreLikeThis example shows how to access the IndexReader instance in PrepareSearchSettings. From here you can call docFreq with whatever Terms you want and save the results on a property for later retrieval.
