### ISSUE TITLE
Get native Query from LuceneQueryable

### ISSUE THREAD

**Issue by mouhong** [chriseldredge/Lucene.Net.Linq#9]
Many times I need to get the native Query from LuceneQueryable because I need to do something not yet provided by Lucene.Net.Linq (e.g., facet search). So I think it might be better to add a method/property (e.g., GetNativeQuery())  to LuceneQueryable to return the underlying native Query, and let session.Query() return LuceneQueryable, not IQueryable<T>, so that I can access the Query like this:

var nativeQuery = session.Query().Where(...).GetNativeQuery();

What do you think?

**Comment by chriseldredge** [comment]
I've thought about adding support for faceting but haven't worked on a proof of concept yet. Your idea to allow the client to customize the query before execution is also interesting. I'm not sure when I'll have time to work on either feature though. If you would like to try to implement this and submit a pull request it might be faster.

**Comment by chriseldredge** [comment]
It is now possible to access the Query, and modify it if you desire, by implementing a custom IDocumentMapper as in this sample:

```
public class QueryCapturingDocumentMapper<T> : ReflectionDocumentMapper<T>
{
    public Query Query { get; private set; }

    public QueryCapturingDocumentMapper(Version version)
        : base(version)
    {
    }

    public override void PrepareSearchSettings(IQueryExecutionContext context)
    {
        base.PrepareSearchSettings(context);

        this.Query = context.Query;
    }
}
```

Pass an instance of QueryCapturingDocumentMapper to LuceneDataProvider.AsQueryable, and after executing a query, QueryCapturingDocumentMapper.Query will contain the query that was executed.

Adding faceting support would require broader changes, and would probably only make sense when using a "group by" clause in LINQ. I'm not planning to add this capability right now because it would be somewhat challenging to implement and I'm not sure how useful it would be.
